module DayEight.Test
open Xunit
open MyAssert
open Advent

let sample =
    """
    ............
    ........0...
    .....0......
    .......0....
    ....0.......
    ......A.....
    ............
    ............
    ........A...
    .........A..
    ............
    ............
    
    """

[<Fact>]
let ``Can Parse``() =
    Grid.ofString sample
    |> Assert.FailWith "%A"